sudo: false
language: python

matrix:
  include:
    - python: 3.6
      env: TOX_ENV=py36

install:
  - pip install tox
  - pip install -r requirements.txt

script:
  - tox -e "${TOX_ENV}"

after_success:
  - coverage combine
  - codecov
